# International District Mapper

class InternationalDistrictMapper:
    def __init__(self):
        self.dictionary = {
            " AFG ": "AFGHANISTAN,INTERNATIONAL",
            " Afghanistan ": "AFGHANISTAN,INTERNATIONAL",
            " Kabul ": "AFGHANISTAN,INTERNATIONAL",
            " ALB ": "ALBANIA,INTERNATIONAL",
            " Albania ": "ALBANIA,INTERNATIONAL",
            " Tirana ": "ALBANIA,INTERNATIONAL",
            " Algeria ": "ALGERIA,INTERNATIONAL",
            " Algiers ": "ALGERIA,INTERNATIONAL",
            " DZA ": "ALGERIA,INTERNATIONAL",
            " الجزائر ": "ALGERIA,INTERNATIONAL",
            " Andorra ": "ANDORRA,INTERNATIONAL",
            " Andorra la Vella ": "ANDORRA,INTERNATIONAL",
            " AGO ": "ANGOLA,INTERNATIONAL",
            " Angola ": "ANGOLA,INTERNATIONAL",
            " Luanda ": "ANGOLA,INTERNATIONAL",
            " Antigua and Barbuda ": "ANTIGUA AND BARBUDA,INTERNATIONAL",
            " ATG ": "ANTIGUA AND BARBUDA,INTERNATIONAL",
            " St. John's ": "ANTIGUA AND BARBUDA,INTERNATIONAL",
            " ARG ": "ARGENTINA,INTERNATIONAL",
            " Argentina ": "ARGENTINA,INTERNATIONAL",
            " Buenos Aires ": "ARGENTINA,INTERNATIONAL",
            " ARM ": "ARMENIA,INTERNATIONAL",
            " Armenia ": "ARMENIA,INTERNATIONAL",
            " Yerevan ": "ARMENIA,INTERNATIONAL",
            " AUS ": "AUSTRALIA,INTERNATIONAL",
            " Australia ": "AUSTRALIA,INTERNATIONAL",
            " Canberra ": "AUSTRALIA,INTERNATIONAL",
            " Austria ": "AUSTRIA,INTERNATIONAL",
            " AUT ": "AUSTRIA,INTERNATIONAL",
            " Vienna ": "AUSTRIA,INTERNATIONAL",
            " AZE ": "AZERBAIJAN,INTERNATIONAL",
            " Azerbaijan ": "AZERBAIJAN,INTERNATIONAL",
            " Baku ": "AZERBAIJAN,INTERNATIONAL",
            " Bahamas ": "BAHAMAS,INTERNATIONAL",
            " BHS ": "BAHAMAS,INTERNATIONAL",
            " Nassau ": "BAHAMAS,INTERNATIONAL",
            " Bahrain ": "BAHRAIN,INTERNATIONAL",
            " BHR ": "BAHRAIN,INTERNATIONAL",
            " Manama ": "BAHRAIN,INTERNATIONAL",
            " 🇧🇩 ": "BANGLADESH,BANGLADESH",
            " Bagerhat ": "BANGLADESH,BANGLADESH",
            " Bangladesh ": "BANGLADESH,BANGLADESH",
            " Barguna ": "BANGLADESH,BANGLADESH",
            " Barisal ": "BANGLADESH,BANGLADESH",
            " Barishal ": "BANGLADESH,BANGLADESH",
            " Bengladesh ": "BANGLADESH,BANGLADESH",
            " BGD ": "BANGLADESH,BANGLADESH",
            " Bogra ": "BANGLADESH,BANGLADESH",
            " Brahmanbaria ": "BANGLADESH,BANGLADESH",
            " Chandpur ": "BANGLADESH,BANGLADESH",
            " Chapainawabganj ": "BANGLADESH,BANGLADESH",
            " Chattogram ": "BANGLADESH,BANGLADESH",
            " Chirirbandar ": "BANGLADESH,BANGLADESH",
            " Chittagong ": "BANGLADESH,BANGLADESH",
            " Chuadanga ": "BANGLADESH,BANGLADESH",
            " Comilla ": "BANGLADESH,BANGLADESH",
            " Cox'sBazar ": "BANGLADESH,BANGLADESH",
            " Dhaka ": "BANGLADESH,BANGLADESH",
            " Dinajpur ": "BANGLADESH,BANGLADESH",
            " Faridpur ": "BANGLADESH,BANGLADESH",
            " Gafargaon ": "BANGLADESH,BANGLADESH",
            " Gaibandha ": "BANGLADESH,BANGLADESH",
            " Gazipur ": "BANGLADESH,BANGLADESH",
            " Gopalganj ": "BANGLADESH,BANGLADESH",
            " Habiganj ": "BANGLADESH,BANGLADESH",
            " Jamalpur ": "BANGLADESH,BANGLADESH",
            " Jessore ": "BANGLADESH,BANGLADESH",
            " Jessore ": "BANGLADESH,BANGLADESH",
            " Jhalokati ": "BANGLADESH,BANGLADESH",
            " Joypurhat ": "BANGLADESH,BANGLADESH",
            " khagrachari ": "BANGLADESH,BANGLADESH",
            " Khulna ": "BANGLADESH,BANGLADESH",
            " Kishoreganj ": "BANGLADESH,BANGLADESH",
            " kotalipara ": "BANGLADESH,BANGLADESH",
            " Kurigram ": "BANGLADESH,BANGLADESH",
            " Kushtia ": "BANGLADESH,BANGLADESH",
            " Lakshmipur ": "BANGLADESH,BANGLADESH",
            " Lalmonirhat ": "BANGLADESH,BANGLADESH",
            " Magura ": "BANGLADESH,BANGLADESH",
            " Manikganj ": "BANGLADESH,BANGLADESH",
            " Mirpur Dhaka ": "BANGLADESH,BANGLADESH",
            " Moulvibazar ": "BANGLADESH,BANGLADESH",
            " Munshiganj ": "BANGLADESH,BANGLADESH",
            " Mymensingh ": "BANGLADESH,BANGLADESH",
            " Naogaon ": "BANGLADESH,BANGLADESH",
            " Narail ": "BANGLADESH,BANGLADESH",
            " Narayanganj ": "BANGLADESH,BANGLADESH",
            " Narsingdi ": "BANGLADESH,BANGLADESH",
            " Natore ": "BANGLADESH,BANGLADESH",
            " Netrokona ": "BANGLADESH,BANGLADESH",
            " Nilphamari ": "BANGLADESH,BANGLADESH",
            " Noakhali ": "BANGLADESH,BANGLADESH",
            " Pabna ": "BANGLADESH,BANGLADESH",
            " Pabna Sadar ": "BANGLADESH,BANGLADESH",
            " Panchagarh ": "BANGLADESH,BANGLADESH",
            " Patuakhali ": "BANGLADESH,BANGLADESH",
            " Rajbari ": "BANGLADESH,BANGLADESH",
            " Rajshahi ": "BANGLADESH,BANGLADESH",
            " Rangamati ": "BANGLADESH,BANGLADESH",
            " Satkhira ": "BANGLADESH,BANGLADESH",
            " setabgonj dinaajpur ": "BANGLADESH,BANGLADESH",
            " Shariatpur ": "BANGLADESH,BANGLADESH",
            " Sherpur ": "BANGLADESH,BANGLADESH",
            " Sirajganj ": "BANGLADESH,BANGLADESH",
            " Sunamganj ": "BANGLADESH,BANGLADESH",
            " Sylhet ": "BANGLADESH,BANGLADESH",
            " SYLHET ": "BANGLADESH,BANGLADESH",
            " Thakurgaon ": "BANGLADESH,BANGLADESH",
            " কক্সবাজার ": "BANGLADESH,BANGLADESH",
            " কিশোরগঞ্জ ": "BANGLADESH,BANGLADESH",
            " কুড়িগ্রাম ": "BANGLADESH,BANGLADESH",
            " কুমিল্লা ": "BANGLADESH,BANGLADESH",
            " কুষ্টিয়া ": "BANGLADESH,BANGLADESH",
            " খাগড়াছড়ি ": "BANGLADESH,BANGLADESH",
            " খুলনা ": "BANGLADESH,BANGLADESH",
            " গফরগাঁও ": "BANGLADESH,BANGLADESH",
            " গাজীপুর ": "BANGLADESH,BANGLADESH",
            " গোপালগঞ্জ ": "BANGLADESH,BANGLADESH",
            " চট্টগ্রাম ": "BANGLADESH,BANGLADESH",
            " চট্রগ্রাম ": "BANGLADESH,BANGLADESH",
            " চন্দ্রগঞ্জ ": "BANGLADESH,BANGLADESH",
            " চাঁপাইনবাবগঞ্জ ": "BANGLADESH,BANGLADESH",
            " চা্ঁদপুর ": "BANGLADESH,BANGLADESH",
            " চিরিরবন্দর ": "BANGLADESH,BANGLADESH",
            " চুয়াডাঙ্গা ": "BANGLADESH,BANGLADESH",
            " জয়পুরহাট ": "BANGLADESH,BANGLADESH",
            " জিঃচা্ঁদপুর ": "BANGLADESH,BANGLADESH",
            " ঝালকাঠি ": "BANGLADESH,BANGLADESH",
            " ঝিনাইদহ ": "BANGLADESH,BANGLADESH",
            " টাঙ্গাইল ": "BANGLADESH,BANGLADESH",
            " ঢাকা ": "BANGLADESH,BANGLADESH",
            " নওগাঁ ": "BANGLADESH,BANGLADESH",
            " নওগাঁ ": "BANGLADESH,BANGLADESH",
            " নড়াইল ": "BANGLADESH,BANGLADESH",
            " নরসিংদী ": "BANGLADESH,BANGLADESH",
            " নরসিংদী শিবপুর ": "BANGLADESH,BANGLADESH",
            " নাটোর ": "BANGLADESH,BANGLADESH",
            " নারায়ণগঞ্জ ": "BANGLADESH,BANGLADESH",
            " নারায়ণগঞ্জ ": "BANGLADESH,BANGLADESH",
            " নীলফামারী ": "BANGLADESH,BANGLADESH",
            " নেত্রকোণা ": "BANGLADESH,BANGLADESH",
            " নেত্রকোনা ": "BANGLADESH,BANGLADESH",
            " নোয়াখালী ": "BANGLADESH,BANGLADESH",
            " পটুয়াখালী ": "BANGLADESH,BANGLADESH",
            " পাবনা ": "BANGLADESH,BANGLADESH",
            " পাবনা সদর ": "BANGLADESH,BANGLADESH",
            " পাবনা সদর উপজেলা ": "BANGLADESH,BANGLADESH",
            " পিরোজপুর ": "BANGLADESH,BANGLADESH",
            " ফেনী ": "BANGLADESH,BANGLADESH",
            " বগুড়া ": "BANGLADESH,BANGLADESH",
            " বরগুনা ": "BANGLADESH,BANGLADESH",
            " বরিশাল ": "BANGLADESH,BANGLADESH",
            " বাগেরহাট ": "BANGLADESH,BANGLADESH",
            " বান্দরবান ": "BANGLADESH,BANGLADESH",
            " বাংলাদেশ ": "BANGLADESH,BANGLADESH",
            " ব্রাহ্মণবাড়িয়া ": "BANGLADESH,BANGLADESH",
            " ব্রাহ্মণবাড়ীয়া ": "BANGLADESH,BANGLADESH",
            " ভোলা ": "BANGLADESH,BANGLADESH",
            " ময়মনসিংহ ": "BANGLADESH,BANGLADESH",
            " মাগুরা ": "BANGLADESH,BANGLADESH",
            " মাদারীপুর ": "BANGLADESH,BANGLADESH",
            " মানিকগঞ্জ ": "BANGLADESH,BANGLADESH",
            " মেহেরপুর ": "BANGLADESH,BANGLADESH",
            " যশোর ": "BANGLADESH,BANGLADESH",
            " রাঙ্গামাটি ": "BANGLADESH,BANGLADESH",
            " রাজশাহী ": "BANGLADESH,BANGLADESH",
            " লক্ষ্মীপুর ": "BANGLADESH,BANGLADESH",
            " লালমনিরহাট ": "BANGLADESH,BANGLADESH",
            " শিবপুর ": "BANGLADESH,BANGLADESH",
            " শেরপুর ": "BANGLADESH,BANGLADESH",
            " সাতক্ষীরা ": "BANGLADESH,BANGLADESH",
            " সিরাজগঞ্জ ": "BANGLADESH,BANGLADESH",
            " Barbados ": "BARBADOS,INTERNATIONAL",
            " BRB ": "BARBADOS,INTERNATIONAL",
            " Bridgetown ": "BARBADOS,INTERNATIONAL",
            " Belarus ": "BELARUS,INTERNATIONAL",
            " BLR ": "BELARUS,INTERNATIONAL",
            " Minsk ": "BELARUS,INTERNATIONAL",
            " BEL ": "BELGIUM,INTERNATIONAL",
            " Belgium ": "BELGIUM,INTERNATIONAL",
            " Brussels ": "BELGIUM,INTERNATIONAL",
            " Belize ": "BELIZE,INTERNATIONAL",
            " Belmopan ": "BELIZE,INTERNATIONAL",
            " BLZ ": "BELIZE,INTERNATIONAL",
            " BEN ": "BENIN,INTERNATIONAL",
            " Benin ": "BENIN,INTERNATIONAL",
            " Porto Novo ": "BENIN,INTERNATIONAL",
            " Bhutan ": "BHUTAN,INTERNATIONAL",
            " BTN ": "BHUTAN,INTERNATIONAL",
            " Thimphu ": "BHUTAN,INTERNATIONAL",
            " BOL ": "BOLIVIA,INTERNATIONAL",
            " Bolivia ": "BOLIVIA,INTERNATIONAL",
            " Sucre ": "BOLIVIA,INTERNATIONAL",
            " BIH ": "BOSNIA AND HERZEGOVINA,INTERNATIONAL",
            " Bosnia and Herzegovina ": "BOSNIA AND HERZEGOVINA,INTERNATIONAL",
            " Sarajevo ": "BOSNIA AND HERZEGOVINA,INTERNATIONAL",
            " Botswana ": "BOTSWANA,INTERNATIONAL",
            " BWA ": "BOTSWANA,INTERNATIONAL",
            " Gaborone ": "BOTSWANA,INTERNATIONAL",
            " BRA ": "BRAZIL,INTERNATIONAL",
            " Brasilia ": "BRAZIL,INTERNATIONAL",
            " Brazil ": "BRAZIL,INTERNATIONAL",
            " Bandar Seri Begawan ": "BRUNEI,INTERNATIONAL",
            " BRN ": "BRUNEI,INTERNATIONAL",
            " Brunei ": "BRUNEI,INTERNATIONAL",
            " BGR ": "BULGARIA,INTERNATIONAL",
            " Bulgaria ": "BULGARIA,INTERNATIONAL",
            " Sofia ": "BULGARIA,INTERNATIONAL",
            " BFA ": "BURKINA FASO,INTERNATIONAL",
            " Burkina Faso ": "BURKINA FASO,INTERNATIONAL",
            " Ouagadougou ": "BURKINA FASO,INTERNATIONAL",
            " BDI ": "BURUNDI,INTERNATIONAL",
            " Bujumbura ": "BURUNDI,INTERNATIONAL",
            " Burundi ": "BURUNDI,INTERNATIONAL",
            " Cambodia ": "CAMBODIA,INTERNATIONAL",
            " KHM ": "CAMBODIA,INTERNATIONAL",
            " Phnom Penh ": "CAMBODIA,INTERNATIONAL",
            " Cameroon ": "CAMEROON,INTERNATIONAL",
            " CMR ": "CAMEROON,INTERNATIONAL",
            " Yaounde ": "CAMEROON,INTERNATIONAL",
            " Canada ": "CANADA,INTERNATIONAL",
            " Ottawa ": "CANADA,INTERNATIONAL",
            " Cape Verde ": "CAPE VERDE,INTERNATIONAL",
            " CPV ": "CAPE VERDE,INTERNATIONAL",
            " Praia ": "CAPE VERDE,INTERNATIONAL",
            " Bangui ": "CENTRAL AFRICAN REPUBLIC,INTERNATIONAL",
            " CAF ": "CENTRAL AFRICAN REPUBLIC,INTERNATIONAL",
            " Central African Republic ": "CENTRAL AFRICAN REPUBLIC,INTERNATIONAL",
            " Chad ": "CHAD,INTERNATIONAL",
            " N'Djamena ": "CHAD,INTERNATIONAL",
            " TCD ": "CHAD,INTERNATIONAL",
            " Chile ": "CHILE,INTERNATIONAL",
            " CHL ": "CHILE,INTERNATIONAL",
            " Santiago ": "CHILE,INTERNATIONAL",
            " Beijing ": "CHINA,INTERNATIONAL",
            " China ": "CHINA,INTERNATIONAL",
            " CHN ": "CHINA,INTERNATIONAL",
            " Bogota ": "COLOMBIA,INTERNATIONAL",
            " COL ": "COLOMBIA,INTERNATIONAL",
            " Colombia ": "COLOMBIA,INTERNATIONAL",
            " Comoros ": "COMOROS,INTERNATIONAL",
            " Moroni ": "COMOROS,INTERNATIONAL",
            " Costa Rica ": "COSTA RICA,INTERNATIONAL",
            " CRI ": "COSTA RICA,INTERNATIONAL",
            " San Jose ": "COSTA RICA,INTERNATIONAL",
            " Croatia ": "CROATIA,INTERNATIONAL",
            " HRV ": "CROATIA,INTERNATIONAL",
            " Zagreb ": "CROATIA,INTERNATIONAL",
            " CUB ": "CUBA,INTERNATIONAL",
            " Cuba ": "CUBA,INTERNATIONAL",
            " Havana ": "CUBA,INTERNATIONAL",
            " CYP ": "CYPRUS,INTERNATIONAL",
            " Cyprus ": "CYPRUS,INTERNATIONAL",
            " Nicosia ": "CYPRUS,INTERNATIONAL",
            " CZE ": "CZECH REPUBLIC,INTERNATIONAL",
            " Czech Republic ": "CZECH REPUBLIC,INTERNATIONAL",
            " Prague ": "CZECH REPUBLIC,INTERNATIONAL",
            " Democratic Republic of Congo ": "DEMOCRATIC REPUBLIC OF CONGO,INTERNATIONAL",
            " Kinshasa ": "DEMOCRATIC REPUBLIC OF CONGO,INTERNATIONAL",
            " Copenagen ": "DENMARK,INTERNATIONAL",
            " Denmark ": "DENMARK,INTERNATIONAL",
            " DNK ": "DENMARK,INTERNATIONAL",
            " DJI ": "DJIBOUTI,INTERNATIONAL",
            " Djibouti ": "DJIBOUTI,INTERNATIONAL",
            " DMA ": "DOMINICA,INTERNATIONAL",
            " Dominica ": "DOMINICA,INTERNATIONAL",
            " Roseau ": "DOMINICA,INTERNATIONAL",
            " DOM ": "DOMINICAN REPUBLIC,INTERNATIONAL",
            " Dominican Republic ": "DOMINICAN REPUBLIC,INTERNATIONAL",
            " Santo Domingo ": "DOMINICAN REPUBLIC,INTERNATIONAL",
            " Dili ": "EAST TIMOR,INTERNATIONAL",
            " East Timor ": "EAST TIMOR,INTERNATIONAL",
            " TLS ": "EAST TIMOR,INTERNATIONAL",
            " ECU ": "ECUADOR,INTERNATIONAL",
            " Ecuador ": "ECUADOR,INTERNATIONAL",
            " Quito ": "ECUADOR,INTERNATIONAL",
            " Cairo ": "EGYPT,INTERNATIONAL",
            " EGY ": "EGYPT,INTERNATIONAL",
            " Egypt ": "EGYPT,INTERNATIONAL",
            " El Salvador ": "EL SALVADOR,INTERNATIONAL",
            " San Salvador ": "EL SALVADOR,INTERNATIONAL",
            " SLV ": "EL SALVADOR,INTERNATIONAL",
            " Equatorial Guinea ": "EQUATORIAL GUINEA,INTERNATIONAL",
            " GNQ ": "EQUATORIAL GUINEA,INTERNATIONAL",
            " Malabo ": "EQUATORIAL GUINEA,INTERNATIONAL",
            " Asmara ": "ERITREA,INTERNATIONAL",
            " ERI ": "ERITREA,INTERNATIONAL",
            " Eritrea ": "ERITREA,INTERNATIONAL",
            " EST ": "ESTONIA,INTERNATIONAL",
            " Estonia ": "ESTONIA,INTERNATIONAL",
            " Tallinn ": "ESTONIA,INTERNATIONAL",
            " Eswatini ": "ESWATINI,INTERNATIONAL",
            " Mbabane ": "ESWATINI,INTERNATIONAL",
            " SWZ ": "ESWATINI,INTERNATIONAL",
            " Addis Ababa ": "ETHIOPIA,INTERNATIONAL",
            " ETH ": "ETHIOPIA,INTERNATIONAL",
            " Ethiopia ": "ETHIOPIA,INTERNATIONAL",
            " Fiji ": "FIJI,INTERNATIONAL",
            " FJI ": "FIJI,INTERNATIONAL",
            " Suva ": "FIJI,INTERNATIONAL",
            " FIN ": "FINLAND,INTERNATIONAL",
            " Finland ": "FINLAND,INTERNATIONAL",
            " Helsinki ": "FINLAND,INTERNATIONAL",
            " FRA ": "FRANCE,INTERNATIONAL",
            " France ": "FRANCE,INTERNATIONAL",
            " Paris ": "FRANCE,INTERNATIONAL",
            " GAB ": "GABON,INTERNATIONAL",
            " Gabon ": "GABON,INTERNATIONAL",
            " Libreville ": "GABON,INTERNATIONAL",
            " Banjul ": "GAMBIA,INTERNATIONAL",
            " Gambia ": "GAMBIA,INTERNATIONAL",
            " GMB ": "GAMBIA,INTERNATIONAL",
            " GEO ": "GEORGIA,INTERNATIONAL",
            " Georgia ": "GEORGIA,INTERNATIONAL",
            " Tbilisi ": "GEORGIA,INTERNATIONAL",
            " Berlin ": "GERMANY,INTERNATIONAL",
            " DEU ": "GERMANY,INTERNATIONAL",
            " Garmany ": "GERMANY,INTERNATIONAL",
            " Germany ": "GERMANY,INTERNATIONAL",
            " जर्मनी ": "GERMANY,INTERNATIONAL",
            " Accra ": "GHANA,INTERNATIONAL",
            " GHA ": "GHANA,INTERNATIONAL",
            " Ghana ": "GHANA,INTERNATIONAL",
            " Athens ": "GREECE,INTERNATIONAL",
            " GRC ": "GREECE,INTERNATIONAL",
            " Greece ": "GREECE,INTERNATIONAL",
            " GRD ": "GRENADA,INTERNATIONAL",
            " Grenada ": "GRENADA,INTERNATIONAL",
            " St. George's ": "GRENADA,INTERNATIONAL",
            " GTM ": "GUATEMALA,INTERNATIONAL",
            " Guatemala ": "GUATEMALA,INTERNATIONAL",
            " Guatemala City ": "GUATEMALA,INTERNATIONAL",
            " Conakry ": "GUINEA,INTERNATIONAL",
            " GIN ": "GUINEA,INTERNATIONAL",
            " Guinea ": "GUINEA,INTERNATIONAL",
            " Bissau ": "GUINEA-BISSAU,INTERNATIONAL",
            " GNB ": "GUINEA-BISSAU,INTERNATIONAL",
            " Guinea-Bissau ": "GUINEA-BISSAU,INTERNATIONAL",
            " Georgetown ": "GUYANA,INTERNATIONAL",
            " GUY ": "GUYANA,INTERNATIONAL",
            " Guyana ": "GUYANA,INTERNATIONAL",
            " Haiti ": "HAITI,INTERNATIONAL",
            " HTI ": "HAITI,INTERNATIONAL",
            " Port-au-Prince ": "HAITI,INTERNATIONAL",
            " HND ": "HONDURAS,INTERNATIONAL",
            " Honduras ": "HONDURAS,INTERNATIONAL",
            " Tegucigalpa ": "HONDURAS,INTERNATIONAL",
            " Budapest ": "HUNGARY,INTERNATIONAL",
            " HUN ": "HUNGARY,INTERNATIONAL",
            " Hungary ": "HUNGARY,INTERNATIONAL",
            " Iceland ": "ICELAND,INTERNATIONAL",
            " ISL ": "ICELAND,INTERNATIONAL",
            " Reykjavík ": "ICELAND,INTERNATIONAL",
            " IDN ": "INDONESIA,INTERNATIONAL",
            " Indonesia ": "INDONESIA,INTERNATIONAL",
            " Jakarta ": "INDONESIA,INTERNATIONAL",
            " Iran ": "IRAN,INTERNATIONAL",
            " IRN ": "IRAN,INTERNATIONAL",
            " Tehran ": "IRAN,INTERNATIONAL",
            " Baghdad ": "IRAQ,INTERNATIONAL",
            " Iraq ": "IRAQ,INTERNATIONAL",
            " IRQ ": "IRAQ,INTERNATIONAL",
            " Dublin ": "IRELAND,INTERNATIONAL",
            " Ireland ": "IRELAND,INTERNATIONAL",
            " IRL ": "IRELAND,INTERNATIONAL",
            " ISR ": "ISRAEL,INTERNATIONAL",
            " Israel ": "ISRAEL,INTERNATIONAL",
            " Jerusalem ": "ISRAEL,INTERNATIONAL",
            " Borgo San Giacomo ": "ITALY,INTERNATIONAL",
            " ITA ": "ITALY,INTERNATIONAL",
            " Italy ": "ITALY,INTERNATIONAL",
            " Modena ": "ITALY,INTERNATIONAL",
            " Rome ": "ITALY,INTERNATIONAL",
            " CIV ": "IVORY COAST,INTERNATIONAL",
            " Ivory Coast ": "IVORY COAST,INTERNATIONAL",
            " Yamoussoukro ": "IVORY COAST,INTERNATIONAL",
            " JAM ": "JAMAICA,INTERNATIONAL",
            " Jamaica ": "JAMAICA,INTERNATIONAL",
            " Kingston ": "JAMAICA,INTERNATIONAL",
            " Japan ": "JAPAN,INTERNATIONAL",
            " JPN ": "JAPAN,INTERNATIONAL",
            " Tokyo ": "JAPAN,INTERNATIONAL",
            " Amman ": "JORDAN,INTERNATIONAL",
            " JOR ": "JORDAN,INTERNATIONAL",
            " Jordan ": "JORDAN,INTERNATIONAL",
            " Astana ": "KAZAKHSTAN,INTERNATIONAL",
            " KAZ ": "KAZAKHSTAN,INTERNATIONAL",
            " Kazakhstan ": "KAZAKHSTAN,INTERNATIONAL",
            " KEN ": "KENYA,INTERNATIONAL",
            " Kenya ": "KENYA,INTERNATIONAL",
            " Nairobi ": "KENYA,INTERNATIONAL",
            " KIR ": "KIRIBATI,INTERNATIONAL",
            " Kiribati ": "KIRIBATI,INTERNATIONAL",
            " Tarawa ": "KIRIBATI,INTERNATIONAL",
            " Kosovo ": "KOSOVO,INTERNATIONAL",
            " Pristina ": "KOSOVO,INTERNATIONAL",
            " Al Farwaniyah ": "KUWAIT,INTERNATIONAL",
            " Farwaniya  Kuwait ": "KUWAIT,INTERNATIONAL",
            " Kuwait City ": "KUWAIT,INTERNATIONAL",
            " KWT ": "KUWAIT,INTERNATIONAL",
            " कुवेत ": "KUWAIT,INTERNATIONAL",
            " Bishkek ": "KYRGYZSTAN,INTERNATIONAL",
            " KGZ ": "KYRGYZSTAN,INTERNATIONAL",
            " Kyrgyzstan ": "KYRGYZSTAN,INTERNATIONAL",
            " LAO ": "LAOS,INTERNATIONAL",
            " Laos ": "LAOS,INTERNATIONAL",
            " Vientiane ": "LAOS,INTERNATIONAL",
            " Latvia ": "LATVIA,INTERNATIONAL",
            " LVA ": "LATVIA,INTERNATIONAL",
            " Riga ": "LATVIA,INTERNATIONAL",
            " Beirut ": "LEBANON,INTERNATIONAL",
            " LBN ": "LEBANON,INTERNATIONAL",
            " Lebanon ": "LEBANON,INTERNATIONAL",
            " Lesotho ": "LESOTHO,INTERNATIONAL",
            " LSO ": "LESOTHO,INTERNATIONAL",
            " Maseru ": "LESOTHO,INTERNATIONAL",
            " LBR ": "LIBERIA,INTERNATIONAL",
            " Liberia ": "LIBERIA,INTERNATIONAL",
            " Monrovia ": "LIBERIA,INTERNATIONAL",
            " LBY ": "LIBYA,INTERNATIONAL",
            " Libya ": "LIBYA,INTERNATIONAL",
            " Tripoli ": "LIBYA,INTERNATIONAL",
            " Liechtenstein ": "LIECHTENSTEIN,INTERNATIONAL",
            " Vaduz ": "LIECHTENSTEIN,INTERNATIONAL",
            " Lithuania ": "LITHUANIA,INTERNATIONAL",
            " LTU ": "LITHUANIA,INTERNATIONAL",
            " Vilnius ": "LITHUANIA,INTERNATIONAL",
            " Luxembourg ": "LUXEMBOURG,INTERNATIONAL",
            " Luxembourg ": "LUXEMBOURG,INTERNATIONAL",
            " Antananarivo ": "MADAGASCAR,INTERNATIONAL",
            " Madagascar ": "MADAGASCAR,INTERNATIONAL",
            " MDG ": "MADAGASCAR,INTERNATIONAL",
            " Lilongwe ": "MALAWI,INTERNATIONAL",
            " Malawi ": "MALAWI,INTERNATIONAL",
            " MWI ": "MALAWI,INTERNATIONAL",
            " Kuala Lumpur ": "MALAYSIA,INTERNATIONAL",
            " Malaysia ": "MALAYSIA,INTERNATIONAL",
            " Maleysiya ": "MALAYSIA,INTERNATIONAL",
            " MYS ": "MALAYSIA,INTERNATIONAL",
            " मलेसिया ": "MALAYSIA,INTERNATIONAL",
            " मलेसियामा ": "MALAYSIA,INTERNATIONAL",
            " Maldives ": "MALDIVES,INTERNATIONAL",
            " Malé ": "MALDIVES,INTERNATIONAL",
            " MDV ": "MALDIVES,INTERNATIONAL",
            " Bamako ": "MALI,INTERNATIONAL",
            " Mali ": "MALI,INTERNATIONAL",
            " MLI ": "MALI,INTERNATIONAL",
            " Malta ": "MALTA,INTERNATIONAL",
            " MLT ": "MALTA,INTERNATIONAL",
            " Valletta ": "MALTA,INTERNATIONAL",
            " Majuro ": "MARSHALL ISLANDS,INTERNATIONAL",
            " Marshall Islands ": "MARSHALL ISLANDS,INTERNATIONAL",
            " MHL ": "MARSHALL ISLANDS,INTERNATIONAL",
            " Mauritania ": "MAURITANIA,INTERNATIONAL",
            " MRT ": "MAURITANIA,INTERNATIONAL",
            " Nouakchott ": "MAURITANIA,INTERNATIONAL",
            " Flacq ": "MAURITIUS,INTERNATIONAL",
            " Mauritius ": "MAURITIUS,INTERNATIONAL",
            " MUS ": "MAURITIUS,INTERNATIONAL",
            " Port Louis ": "MAURITIUS,INTERNATIONAL",
            " MEX ": "MEXICO,INTERNATIONAL",
            " Mexico ": "MEXICO,INTERNATIONAL",
            " Mexico City ": "MEXICO,INTERNATIONAL",
            " FSM ": "MICRONESIA,INTERNATIONAL",
            " Micronesia ": "MICRONESIA,INTERNATIONAL",
            " Palikir ": "MICRONESIA,INTERNATIONAL",
            " Chisinau ": "MOLDOVA,INTERNATIONAL",
            " MDA ": "MOLDOVA,INTERNATIONAL",
            " Moldova ": "MOLDOVA,INTERNATIONAL",
            " MCO ": "MONACO,INTERNATIONAL",
            " Monaco ": "MONACO,INTERNATIONAL",
            " Monaco ": "MONACO,INTERNATIONAL",
            " MNG ": "MONGOLIA,INTERNATIONAL",
            " Mongolia ": "MONGOLIA,INTERNATIONAL",
            " Ulaanbaatar ": "MONGOLIA,INTERNATIONAL",
            " MNE ": "MONTENEGRO,INTERNATIONAL",
            " Montenegro ": "MONTENEGRO,INTERNATIONAL",
            " Podgorica ": "MONTENEGRO,INTERNATIONAL",
            " FEZ ": "MOROCCO,INTERNATIONAL",
            " MAR ": "MOROCCO,INTERNATIONAL",
            " Morocco ": "MOROCCO,INTERNATIONAL",
            " Rabat ": "MOROCCO,INTERNATIONAL",
            " المغرب ": "MOROCCO,INTERNATIONAL",
            " فاس ": "MOROCCO,INTERNATIONAL",
            " Maputo ": "MOZAMBIQUE,INTERNATIONAL",
            " MOZ ": "MOZAMBIQUE,INTERNATIONAL",
            " Mozambique ": "MOZAMBIQUE,INTERNATIONAL",
            " MMR ": "MYANMAR,INTERNATIONAL",
            " Myanmar ": "MYANMAR,INTERNATIONAL",
            " Naypyidaw ": "MYANMAR,INTERNATIONAL",
            " Namibia ": "NAMIBIA,INTERNATIONAL",
            " Windhoek ": "NAMIBIA,INTERNATIONAL",
            " Nauru ": "NAURU,INTERNATIONAL",
            " NRU ": "NAURU,INTERNATIONAL",
            " Yaren ": "NAURU,INTERNATIONAL",
            " 🇳🇵": "NEPAL,INTERNATIONAL",
            " Achham ": "NEPAL,INTERNATIONAL",
            " Amaragadhi ": "NEPAL,INTERNATIONAL",
            " Arghakhanchi ": "NEPAL,INTERNATIONAL",
            " Baglung ": "NEPAL,INTERNATIONAL",
            " Bagmati ": "NEPAL,INTERNATIONAL",
            " Baitadi ": "NEPAL,INTERNATIONAL",
            " Bajhang ": "NEPAL,INTERNATIONAL",
            " Bajura ": "NEPAL,INTERNATIONAL",
            " Banepa ": "NEPAL,INTERNATIONAL",
            " Banke ": "NEPAL,INTERNATIONAL",
            " Bara ": "NEPAL,INTERNATIONAL",
            " Bardiya ": "NEPAL,INTERNATIONAL",
            " Bhadrapur ": "NEPAL,INTERNATIONAL",
            " Bhaktapur ": "NEPAL,INTERNATIONAL",
            " Bhaktapur  ": "NEPAL,INTERNATIONAL",
            " Bharatpur ": "NEPAL,INTERNATIONAL",
            " Bhojpur ": "NEPAL,INTERNATIONAL",
            " Biratnagar ": "NEPAL,INTERNATIONAL",
            " Birendranagar ": "NEPAL,INTERNATIONAL",
            " Birganj ": "NEPAL,INTERNATIONAL",
            " Birtamod ": "NEPAL,INTERNATIONAL",
            " Butwal ": "NEPAL,INTERNATIONAL",
            " Chitwan ": "NEPAL,INTERNATIONAL",
            " Dadeldhura ": "NEPAL,INTERNATIONAL",
            " Dailekh  ": "NEPAL,INTERNATIONAL",
            " Damak ": "NEPAL,INTERNATIONAL",
            " Dang ": "NEPAL,INTERNATIONAL",
            " Darchula ": "NEPAL,INTERNATIONAL",
            " Dhading ": "NEPAL,INTERNATIONAL",
            " Dhangadhi ": "NEPAL,INTERNATIONAL",
            " Dhankuta ": "NEPAL,INTERNATIONAL",
            " Dhanusa ": "NEPAL,INTERNATIONAL",
            " Dharan ": "NEPAL,INTERNATIONAL",
            " Dhulikhel ": "NEPAL,INTERNATIONAL",
            " Dipayal-Silgadhi ": "NEPAL,INTERNATIONAL",
            " Dolakha ": "NEPAL,INTERNATIONAL",
            " Dolpa  ": "NEPAL,INTERNATIONAL",
            " Doti ": "NEPAL,INTERNATIONAL",
            " Gandaki ": "NEPAL,INTERNATIONAL",
            " Ghorahi ": "NEPAL,INTERNATIONAL",
            " Gorkha ": "NEPAL,INTERNATIONAL",
            " Gulariya ": "NEPAL,INTERNATIONAL",
            " Gulmi ": "NEPAL,INTERNATIONAL",
            " Hetauda ": "NEPAL,INTERNATIONAL",
            " Humla  ": "NEPAL,INTERNATIONAL",
            " Ilam ": "NEPAL,INTERNATIONAL",
            " Inaruwa ": "NEPAL,INTERNATIONAL",
            " Itahari ": "NEPAL,INTERNATIONAL",
            " Jajarkot  ": "NEPAL,INTERNATIONAL",
            " Jaleswar ": "NEPAL,INTERNATIONAL",
            " Janakpur ": "NEPAL,INTERNATIONAL",
            " Jhapa ": "NEPAL,INTERNATIONAL",
            " Jumla  ": "NEPAL,INTERNATIONAL",
            " Kailali ": "NEPAL,INTERNATIONAL",
            " kalaiya ": "NEPAL,INTERNATIONAL",
            " Kalikot  ": "NEPAL,INTERNATIONAL",
            " Kanchanpur ": "NEPAL,INTERNATIONAL",
            " Kapilvastu ": "NEPAL,INTERNATIONAL",
            " Karnali ": "NEPAL,INTERNATIONAL",
            " Kaski ": "NEPAL,INTERNATIONAL",
            " Kathmandu ": "NEPAL,INTERNATIONAL",
            " Kathmandu ": "NEPAL,INTERNATIONAL",
            " Kavrepalanchok ": "NEPAL,INTERNATIONAL",
            " Khotang ": "NEPAL,INTERNATIONAL",
            " Kirtipur ": "NEPAL,INTERNATIONAL",
            " Lahan ": "NEPAL,INTERNATIONAL",
            " Lalitpur ": "NEPAL,INTERNATIONAL",
            " Lamjung ": "NEPAL,INTERNATIONAL",
            " Lumbini ": "NEPAL,INTERNATIONAL",
            " Madhyapur Thimi ": "NEPAL,INTERNATIONAL",
            " Mahottari ": "NEPAL,INTERNATIONAL",
            " Makawanpur ": "NEPAL,INTERNATIONAL",
            " Malangwa ": "NEPAL,INTERNATIONAL",
            " Manang ": "NEPAL,INTERNATIONAL",
            " Mechinagar ": "NEPAL,INTERNATIONAL",
            " Morang ": "NEPAL,INTERNATIONAL",
            " Mugu  ": "NEPAL,INTERNATIONAL",
            " Mustang ": "NEPAL,INTERNATIONAL",
            " Myagdi ": "NEPAL,INTERNATIONAL",
            " Nawalpur ": "NEPAL,INTERNATIONAL",
            " Nepal ": "NEPAL,INTERNATIONAL",
            " NEPAL ": "NEPAL,INTERNATIONAL",
            " NEPAL ": "NEPAL,INTERNATIONAL",
            " nepal ": "NEPAL,INTERNATIONAL",
            " Nepalganj ": "NEPAL,INTERNATIONAL",
            " NP ": "NEPAL,INTERNATIONAL",
            " NPL ": "NEPAL,INTERNATIONAL",
            " Nuwakot  ": "NEPAL,INTERNATIONAL",
            " Okhaldhunga ": "NEPAL,INTERNATIONAL",
            " Palpa ": "NEPAL,INTERNATIONAL",
            " Panauti ": "NEPAL,INTERNATIONAL",
            " Panchthar ": "NEPAL,INTERNATIONAL",
            " Parasi ": "NEPAL,INTERNATIONAL",
            " Parbat ": "NEPAL,INTERNATIONAL",
            " Parsa ": "NEPAL,INTERNATIONAL",
            " Pokhara ": "NEPAL,INTERNATIONAL",
            " Putalibazar ": "NEPAL,INTERNATIONAL",
            " Pyuthan ": "NEPAL,INTERNATIONAL",
            " Rajbiraj ": "NEPAL,INTERNATIONAL",
            " Ramechhap ": "NEPAL,INTERNATIONAL",
            " Rasuwa ": "NEPAL,INTERNATIONAL",
            " Ratnanagar ": "NEPAL,INTERNATIONAL",
            " Rautahat ": "NEPAL,INTERNATIONAL",
            " Rolpa ": "NEPAL,INTERNATIONAL",
            " Rukum ": "NEPAL,INTERNATIONAL",
            " Rukum Paschim  ": "NEPAL,INTERNATIONAL",
            " Rupandehi ": "NEPAL,INTERNATIONAL",
            " Salyan  ": "NEPAL,INTERNATIONAL",
            " Sankhuwasabha ": "NEPAL,INTERNATIONAL",
            " Saptari ": "NEPAL,INTERNATIONAL",
            " Sarlahi ": "NEPAL,INTERNATIONAL",
            " Siddharthanagar ": "NEPAL,INTERNATIONAL",
            " Sindhuli ": "NEPAL,INTERNATIONAL",
            " Sindhupalchok ": "NEPAL,INTERNATIONAL",
            " Siraha ": "NEPAL,INTERNATIONAL",
            " Solukhumbu ": "NEPAL,INTERNATIONAL",
            " Sudur-Paschim ": "NEPAL,INTERNATIONAL",
            " Sunsari ": "NEPAL,INTERNATIONAL",
            " Surkhet  ": "NEPAL,INTERNATIONAL",
            " Syangja ": "NEPAL,INTERNATIONAL",
            " Tanahu  ": "NEPAL,INTERNATIONAL",
            " Tansen ": "NEPAL,INTERNATIONAL",
            " Taplejung ": "NEPAL,INTERNATIONAL",
            " Terhathum ": "NEPAL,INTERNATIONAL",
            " Tikapur ": "NEPAL,INTERNATIONAL",
            " Triyuga ": "NEPAL,INTERNATIONAL",
            " Tulsipur ": "NEPAL,INTERNATIONAL",
            " Udayapur ": "NEPAL,INTERNATIONAL",
            " Waling ": "NEPAL,INTERNATIONAL",
            " नेपाल ": "NEPAL,INTERNATIONAL",
            "🇳🇵": "NEPAL,INTERNATIONAL",
            "🇳🇵🇳🇵": "NEPAL,INTERNATIONAL",
            "Jkr 🇳🇵": "NEPAL,INTERNATIONAL",
            "Nepal🇳🇵🇳🇵": "NEPAL,INTERNATIONAL",
            " Amsterdam ": "NETHERLANDS,INTERNATIONAL",
            " nederland ": "NETHERLANDS,INTERNATIONAL",
            " Netherlands ": "NETHERLANDS,INTERNATIONAL",
            " NLD ": "NETHERLANDS,INTERNATIONAL",
            " New Zealand ": "NEW ZEALAND,INTERNATIONAL",
            " NZL ": "NEW ZEALAND,INTERNATIONAL",
            " Wellington ": "NEW ZEALAND,INTERNATIONAL",
            " Managua ": "NICARAGUA,INTERNATIONAL",
            " NIC ": "NICARAGUA,INTERNATIONAL",
            " Nicaragua ": "NICARAGUA,INTERNATIONAL",
            " NER ": "NIGER,INTERNATIONAL",
            " Niamey ": "NIGER,INTERNATIONAL",
            " Niger ": "NIGER,INTERNATIONAL",
            " Abuja ": "NIGERIA,INTERNATIONAL",
            " NGA ": "NIGERIA,INTERNATIONAL",
            " Nigeria ": "NIGERIA,INTERNATIONAL",
            " Korea": "NORTH KOREA,INTERNATIONAL",
            " North ": "NORTH KOREA,INTERNATIONAL",
            " NORTH KOREA ": "NORTH KOREA,INTERNATIONAL",
            " PRK ": "NORTH KOREA,INTERNATIONAL",
            " Pyongyang ": "NORTH KOREA,INTERNATIONAL",
            " MKD ": "NORTH MACEDONIA,INTERNATIONAL",
            " North Macedonia ": "NORTH MACEDONIA,INTERNATIONAL",
            " Skopje ": "NORTH MACEDONIA,INTERNATIONAL",
            " NOR ": "NORWAY,INTERNATIONAL",
            " Norway ": "NORWAY,INTERNATIONAL",
            " Oslo ": "NORWAY,INTERNATIONAL",
            " Muscat ": "OMAN,INTERNATIONAL",
            " Oman ": "OMAN,INTERNATIONAL",
            " OMN ": "OMAN,INTERNATIONAL",
            " Azad Kashmir ": "PAKISTAN,INTERNATIONAL",
            " Country Pakistan ": "PAKISTAN,INTERNATIONAL",
            " Islamabad ": "PAKISTAN,INTERNATIONAL",
            " khanewal ": "PAKISTAN,INTERNATIONAL",
            " Mirpur ": "PAKISTAN,INTERNATIONAL",
            " PAK ": "PAKISTAN,INTERNATIONAL",
            " Pakistan ": "PAKISTAN,INTERNATIONAL",
            " Melekeok ": "PALAU,INTERNATIONAL",
            " Palau ": "PALAU,INTERNATIONAL",
            " PLW ": "PALAU,INTERNATIONAL",
            " East Jerusalem ": "PALESTINE,INTERNATIONAL",
            " Palestine ": "PALESTINE,INTERNATIONAL",
            " PSE ": "PALESTINE,INTERNATIONAL",
            " PAN ": "PANAMA,INTERNATIONAL",
            " Panama ": "PANAMA,INTERNATIONAL",
            " Panama City ": "PANAMA,INTERNATIONAL",
            " Papua New Guinea ": "PAPUA NEW GUINEA,INTERNATIONAL",
            " PNG ": "PAPUA NEW GUINEA,INTERNATIONAL",
            " Port Moresby ": "PAPUA NEW GUINEA,INTERNATIONAL",
            " Asunción ": "PARAGUAY,INTERNATIONAL",
            " Paraguay ": "PARAGUAY,INTERNATIONAL",
            " PRY ": "PARAGUAY,INTERNATIONAL",
            " Lima ": "PERU,INTERNATIONAL",
            " PER ": "PERU,INTERNATIONAL",
            " Peru ": "PERU,INTERNATIONAL",
            " Manila ": "PHILIPPINES,INTERNATIONAL",
            " Philippine ": "PHILIPPINES,INTERNATIONAL",
            " Philippines ": "PHILIPPINES,INTERNATIONAL",
            " Phillippines ": "PHILIPPINES,INTERNATIONAL",
            " PHL ": "PHILIPPINES,INTERNATIONAL",
            " Zambales ": "PHILIPPINES,INTERNATIONAL",
            " POL ": "POLAND,INTERNATIONAL",
            " Poland ": "POLAND,INTERNATIONAL",
            " Warsaw ": "POLAND,INTERNATIONAL",
            " Lisbon ": "PORTUGAL,INTERNATIONAL",
            " Portugal ": "PORTUGAL,INTERNATIONAL",
            " PRT ": "PORTUGAL,INTERNATIONAL",
            " Doha ": "QATAR,INTERNATIONAL",
            " QAT ": "QATAR,INTERNATIONAL",
            " Qatar ": "QATAR,INTERNATIONAL",
            " Brazzaville ": "REPUBLIC OF THE CONGO,INTERNATIONAL",
            " COG ": "REPUBLIC OF THE CONGO,INTERNATIONAL",
            " Republic of the Congo ": "REPUBLIC OF THE CONGO,INTERNATIONAL",
            " Bucharest ": "ROMANIA,INTERNATIONAL",
            " Romania ": "ROMANIA,INTERNATIONAL",
            " ROU ": "ROMANIA,INTERNATIONAL",
            " Moscow ": "RUSSIA,INTERNATIONAL",
            " RUS ": "RUSSIA,INTERNATIONAL",
            " Russia ": "RUSSIA,INTERNATIONAL",
            " Kigali ": "RWANDA,INTERNATIONAL",
            " RWA ": "RWANDA,INTERNATIONAL",
            " Rwanda ": "RWANDA,INTERNATIONAL",
            " Basseterre ": "SAINT KITTS AND NEVIS,INTERNATIONAL",
            " KNA ": "SAINT KITTS AND NEVIS,INTERNATIONAL",
            " Saint Kitts and Nevis ": "SAINT KITTS AND NEVIS,INTERNATIONAL",
            " Castries ": "SAINT LUCIA,INTERNATIONAL",
            " LCA ": "SAINT LUCIA,INTERNATIONAL",
            " Saint Lucia ": "SAINT LUCIA,INTERNATIONAL",
            " Kingstown ": "SAINT VINCENT AND THE GRENADINES,INTERNATIONAL",
            " Saint Vincent and the Grenadines ": "SAINT VINCENT AND THE GRENADINES,INTERNATIONAL",
            " VCT ": "SAINT VINCENT AND THE GRENADINES,INTERNATIONAL",
            " Apia ": "SAMOA,INTERNATIONAL",
            " Samoa ": "SAMOA,INTERNATIONAL",
            " WSM ": "SAMOA,INTERNATIONAL",
            " San Marino ": "SAN MARINO,INTERNATIONAL",
            " San Marino ": "SAN MARINO,INTERNATIONAL",
            " SMR ": "SAN MARINO,INTERNATIONAL",
            " Sao Tome ": "SAO TOME AND PRINCIPE,INTERNATIONAL",
            " Sao Tome and Principe ": "SAO TOME AND PRINCIPE,INTERNATIONAL",
            " STP ": "SAO TOME AND PRINCIPE,INTERNATIONAL",
            " Al Khobar ": "SAUDI ARABIA,INTERNATIONAL",
            " Dammam ": "SAUDI ARABIA,INTERNATIONAL",
            " jeddah ": "SAUDI ARABIA,INTERNATIONAL",
            " Khobar ": "SAUDI ARABIA,INTERNATIONAL",
            " Madinah ": "SAUDI ARABIA,INTERNATIONAL",
            " Medina ": "SAUDI ARABIA,INTERNATIONAL",
            " Riyadh ": "SAUDI ARABIA,INTERNATIONAL",
            " SAU ": "SAUDI ARABIA,INTERNATIONAL",
            " saudi ": "SAUDI ARABIA,INTERNATIONAL",
            " Saudi Arab ": "SAUDI ARABIA,INTERNATIONAL",
            " saudi arabaia ": "SAUDI ARABIA,INTERNATIONAL",
            " Saudi Arabia ": "SAUDI ARABIA,INTERNATIONAL",
            " saudi arabiya ": "SAUDI ARABIA,INTERNATIONAL",
            " साउदी ": "SAUDI ARABIA,INTERNATIONAL",
            " Dakar ": "SENEGAL,INTERNATIONAL",
            " Senegal ": "SENEGAL,INTERNATIONAL",
            " Belgrade ": "SERBIA,INTERNATIONAL",
            " Serbia ": "SERBIA,INTERNATIONAL",
            " SRB ": "SERBIA,INTERNATIONAL",
            " Seychelles ": "SEYCHELLES,INTERNATIONAL",
            " SYC ": "SEYCHELLES,INTERNATIONAL",
            " Victoria ": "SEYCHELLES,INTERNATIONAL",
            " Freetown ": "SIERRA LEONE,INTERNATIONAL",
            " Sierra Leone ": "SIERRA LEONE,INTERNATIONAL",
            " SLE ": "SIERRA LEONE,INTERNATIONAL",
            " SGP ": "SINGAPORE,INTERNATIONAL",
            " Singapore ": "SINGAPORE,INTERNATIONAL",
            " Singapore ": "SINGAPORE,INTERNATIONAL",
            " Bratislava ": "SLOVAKIA,INTERNATIONAL",
            " Slovakia ": "SLOVAKIA,INTERNATIONAL",
            " SVK ": "SLOVAKIA,INTERNATIONAL",
            " Ljubljana ": "SLOVENIA,INTERNATIONAL",
            " Slovenia ": "SLOVENIA,INTERNATIONAL",
            " SVN ": "SLOVENIA,INTERNATIONAL",
            " Honiara ": "SOLOMON ISLANDS,INTERNATIONAL",
            " SLB ": "SOLOMON ISLANDS,INTERNATIONAL",
            " Solomon Islands ": "SOLOMON ISLANDS,INTERNATIONAL",
            " Mogadishu ": "SOMALIA,INTERNATIONAL",
            " SOM ": "SOMALIA,INTERNATIONAL",
            " Somalia ": "SOMALIA,INTERNATIONAL",
            " illovo ": "SOUTH AFRICA,INTERNATIONAL",
            " Illovo South ": "SOUTH AFRICA,INTERNATIONAL",
            " Pretoria ": "SOUTH AFRICA,INTERNATIONAL",
            " South Africa ": "SOUTH AFRICA,INTERNATIONAL",
            " ZAF ": "SOUTH AFRICA,INTERNATIONAL",
            " Gyeonggi-do ": "SOUTH KOREA,INTERNATIONAL",
            " KOR ": "SOUTH KOREA,INTERNATIONAL",
            " Korea": "SOUTH KOREA,INTERNATIONAL",
            " Seoul ": "SOUTH KOREA,INTERNATIONAL",
            " South ": "SOUTH KOREA,INTERNATIONAL",
            " South Korea ": "SOUTH KOREA,INTERNATIONAL",
            " Yangju-si ": "SOUTH KOREA,INTERNATIONAL",
            " 경기도 ": "SOUTH KOREA,INTERNATIONAL",
            " 양주시 ": "SOUTH KOREA,INTERNATIONAL",
            " Juba ": "SOUTH SUDAN,INTERNATIONAL",
            " South Sudan ": "SOUTH SUDAN,INTERNATIONAL",
            " SSD ": "SOUTH SUDAN,INTERNATIONAL",
            " ESP ": "SPAIN,INTERNATIONAL",
            " Madrid ": "SPAIN,INTERNATIONAL",
            " Spain ": "SPAIN,INTERNATIONAL",
            " Trinidad ": "SPAIN,INTERNATIONAL",
            " Kandy ": "SRI LANKA,INTERNATIONAL",
            " Katugastota ": "SRI LANKA,INTERNATIONAL",
            " LKA ": "SRI LANKA,INTERNATIONAL",
            " Sire lanka ": "SRI LANKA,INTERNATIONAL",
            " Sri Jayawardenapura Kotte ": "SRI LANKA,INTERNATIONAL",
            " Sri Lanka ": "SRI LANKA,INTERNATIONAL",
            " Srilanka ": "SRI LANKA,INTERNATIONAL",
            " Wadduwa ": "SRI LANKA,INTERNATIONAL",
            " Khartoum ": "SUDAN,INTERNATIONAL",
            " SDN ": "SUDAN,INTERNATIONAL",
            " Sudan ": "SUDAN,INTERNATIONAL",
            " Paramaribo ": "SURINAME,INTERNATIONAL",
            " SUR ": "SURINAME,INTERNATIONAL",
            " Suriname ": "SURINAME,INTERNATIONAL",
            " Stockholm ": "SWEDEN,INTERNATIONAL",
            " SWE ": "SWEDEN,INTERNATIONAL",
            " Sweden ": "SWEDEN,INTERNATIONAL",
            " Bern ": "SWITZERLAND,INTERNATIONAL",
            " CHE ": "SWITZERLAND,INTERNATIONAL",
            " Switzerland ": "SWITZERLAND,INTERNATIONAL",
            " Damascus ": "SYRIA,INTERNATIONAL",
            " SYR ": "SYRIA,INTERNATIONAL",
            " Syria ": "SYRIA,INTERNATIONAL",
            " Taipei ": "TAIWAN,INTERNATIONAL",
            " Taiwan ": "TAIWAN,INTERNATIONAL",
            " TWN ": "TAIWAN,INTERNATIONAL",
            " Dushanbe ": "TAJIKISTAN,INTERNATIONAL",
            " Tajikistan ": "TAJIKISTAN,INTERNATIONAL",
            " TJK ": "TAJIKISTAN,INTERNATIONAL",
            " Dodoma ": "TANZANIA,INTERNATIONAL",
            " Tanzania ": "TANZANIA,INTERNATIONAL",
            " TZA ": "TANZANIA,INTERNATIONAL",
            " Bangkok ": "THAILAND,INTERNATIONAL",
            " THA ": "THAILAND,INTERNATIONAL",
            " Thailand ": "THAILAND,INTERNATIONAL",
            " Lomé ": "TOGO,INTERNATIONAL",
            " TGO ": "TOGO,INTERNATIONAL",
            " Togo ": "TOGO,INTERNATIONAL",
            " Nukualofa ": "TONGA,INTERNATIONAL",
            " TON ": "TONGA,INTERNATIONAL",
            " Tonga ": "TONGA,INTERNATIONAL",
            " Port of Spain ": "TRINIDAD AND TOBAGO,INTERNATIONAL",
            " Trinidad and Tobago ": "TRINIDAD AND TOBAGO,INTERNATIONAL",
            " TTO ": "TRINIDAD AND TOBAGO,INTERNATIONAL",
            " TUN ": "TUNISIA,INTERNATIONAL",
            " Tunis ": "TUNISIA,INTERNATIONAL",
            " Tunisia ": "TUNISIA,INTERNATIONAL",
            " Ankara ": "TURKEY,INTERNATIONAL",
            " TUR ": "TURKEY,INTERNATIONAL",
            " Turkey ": "TURKEY,INTERNATIONAL",
            " Ashgabat ": "TURKMENISTAN,INTERNATIONAL",
            " TKM ": "TURKMENISTAN,INTERNATIONAL",
            " Turkmenistan ": "TURKMENISTAN,INTERNATIONAL",
            " Funafuti ": "TUVALU,INTERNATIONAL",
            " TUV ": "TUVALU,INTERNATIONAL",
            " Tuvalu ": "TUVALU,INTERNATIONAL",
            " Kampala ": "UGANDA,INTERNATIONAL",
            " UGA ": "UGANDA,INTERNATIONAL",
            " Uganda ": "UGANDA,INTERNATIONAL",
            " Kiev ": "UKRAINE,INTERNATIONAL",
            " UKR ": "UKRAINE,INTERNATIONAL",
            " Ukraine ": "UKRAINE,INTERNATIONAL",
            " Abu Dhabi ": "UNITED ARAB EMIRATES,INTERNATIONAL",
            " Abu Dhabi ": "UNITED ARAB EMIRATES,INTERNATIONAL",
            " dubai ": "UNITED ARAB EMIRATES,INTERNATIONAL",
            " Habshan ": "UNITED ARAB EMIRATES,INTERNATIONAL",
            " jebel ali ": "UNITED ARAB EMIRATES,INTERNATIONAL",
            " New Sanaya ": "UNITED ARAB EMIRATES,INTERNATIONAL",
            " saudia Arab ": "UNITED ARAB EMIRATES,INTERNATIONAL",
            " UAE ": "UNITED ARAB EMIRATES,INTERNATIONAL",
            " uae ": "UNITED ARAB EMIRATES,INTERNATIONAL",
            " uae dubai ": "UNITED ARAB EMIRATES,INTERNATIONAL",
            " United Arab Emirates ": "UNITED ARAB EMIRATES,INTERNATIONAL",
            " दुबई ": "UNITED ARAB EMIRATES,INTERNATIONAL",
            " Birmingham ": "UNITED KINGDOM,INTERNATIONAL",
            " England ": "UNITED KINGDOM,INTERNATIONAL",
            " GBR ": "UNITED KINGDOM,INTERNATIONAL",
            " London ": "UNITED KINGDOM,INTERNATIONAL",
            " Northern Ireland ": "UNITED KINGDOM,INTERNATIONAL",
            " Scotland ": "UNITED KINGDOM,INTERNATIONAL",
            " United Kingdom ": "UNITED KINGDOM,INTERNATIONAL",
            " Wales  ": "UNITED KINGDOM,INTERNATIONAL",
            " Wolverhampton ": "UNITED KINGDOM,INTERNATIONAL",
            " California ": "UNITED STATES,INTERNATIONAL",
            " NY ": "UNITED STATES,INTERNATIONAL",
            " Texas ": "UNITED STATES,INTERNATIONAL",
            " U S A": "UNITED STATES,INTERNATIONAL",
            " United States ": "UNITED STATES,INTERNATIONAL",
            " USA ": "UNITED STATES,INTERNATIONAL",
            " Washington D.C. ": "UNITED STATES,INTERNATIONAL",
            " Montevideo ": "URUGUAY,INTERNATIONAL",
            " Uruguay ": "URUGUAY,INTERNATIONAL",
            " URY ": "URUGUAY,INTERNATIONAL",
            " Tashkent ": "UZBEKISTAN,INTERNATIONAL",
            " UZB ": "UZBEKISTAN,INTERNATIONAL",
            " Uzbekistan ": "UZBEKISTAN,INTERNATIONAL",
            " Port Vila ": "VANUATU,INTERNATIONAL",
            " Vanuatu ": "VANUATU,INTERNATIONAL",
            " VUT ": "VANUATU,INTERNATIONAL",
            " VAT ": "VATICAN CITY,INTERNATIONAL",
            " Vatican City ": "VATICAN CITY,INTERNATIONAL",
            " Vatican City ": "VATICAN CITY,INTERNATIONAL",
            " Caracas ": "VENEZUELA,INTERNATIONAL",
            " VEN ": "VENEZUELA,INTERNATIONAL",
            " Venezuela ": "VENEZUELA,INTERNATIONAL",
            " Hanoi ": "VIETNAM,INTERNATIONAL",
            " Vietnam ": "VIETNAM,INTERNATIONAL",
            " VNM ": "VIETNAM,INTERNATIONAL",
            " Sana'a ": "YEMEN,INTERNATIONAL",
            " YEM ": "YEMEN,INTERNATIONAL",
            " Yemen ": "YEMEN,INTERNATIONAL",
            " Lusaka ": "ZAMBIA,INTERNATIONAL",
            " Zambia ": "ZAMBIA,INTERNATIONAL",
            " ZMB ": "ZAMBIA,INTERNATIONAL",
            " Harare ": "ZIMBABWE,INTERNATIONAL",
            " Zimbabwe ": "ZIMBABWE,INTERNATIONAL",
            " ZWE ": "ZIMBABWE,INTERNATIONAL",
        }

    def getKeys(self):
        return self.dictionary.keys()

    def get_dist_state(self, key):
        return self.dictionary.get(key)

    def get_state_dist_from_add_string(self, address):
        for key in self.getKeys():
            if address.find(key.lower()) != -1:
                return self.dictionary.get(key)

    def get_state_dist_from_add_string_by_add_rec(self, address_string):
        address_list_token = address_string.split(" ")
        count = 0
        value = []
        if address_list_token is not None and len(address_list_token) > 0:
            for token in address_list_token:
                if token is not None and len(token) > 0 and self.dictionary.get(token.lower()) is not None:
                    dist_state = self.dictionary.get(token.lower())
                    value.append(dist_state)
        count = len(set(value))
        if count == 1:
            return value[0], count

        dist_state_join = ""
        for item in set(value):
            if len(dist_state_join) > 0:
                dist_state_join = dist_state_join + " & " + item
                continue
            dist_state_join = item
        return dist_state_join, count
